/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Jan 6, 2016, 12:10:53 AM
 */
package gui;

import config.Configuration;
import java.awt.Color;
import javax.swing.JOptionPane;
import service.AdminService;

/**
 *
 * @author nishant
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        adminLoginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        handleLabel = new javax.swing.JLabel();
        handleField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        signupLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 250, 400, 300));
        setMaximizedBounds(new java.awt.Rectangle(300, 250, 400, 300));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jLayeredPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseMoved(evt);
            }
        });

        adminLoginLabel.setFont(new java.awt.Font("Ubuntu", 1, 18));
        adminLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminLoginLabel.setText("ADMIN LOGIN");
        adminLoginLabel.setPreferredSize(new java.awt.Dimension(100, 30));
        adminLoginLabel.setBounds(100, 30, 200, 30);
        jLayeredPane1.add(adminLoginLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        passwordLabel.setFont(new java.awt.Font("Ubuntu", 1, 17));
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("Password");
        passwordLabel.setBounds(40, 140, 100, 30);
        jLayeredPane1.add(passwordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        handleLabel.setFont(new java.awt.Font("Ubuntu", 1, 17));
        handleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        handleLabel.setText("Handle");
        handleLabel.setBounds(40, 80, 100, 30);
        jLayeredPane1.add(handleLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handleField.setBounds(150, 80, 190, 30);
        jLayeredPane1.add(handleField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.setBounds(150, 140, 190, 30);
        jLayeredPane1.add(passwordField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        loginButton.setFont(new java.awt.Font("Ubuntu", 1, 18));
        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.setBounds(140, 200, 120, 40);
        jLayeredPane1.add(loginButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        signupLabel.setFont(new java.awt.Font("Ubuntu", 1, 15));
        signupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signupLabel.setText("New user ? SIGN UP");
        signupLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLabelMouseClicked(evt);
            }
        });
        signupLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                signupLabelMouseMoved(evt);
            }
        });
        signupLabel.setBounds(122, 250, 150, 18);
        jLayeredPane1.add(signupLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    AdminService adminService;
private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_passwordFieldActionPerformed

private void signupLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabelMouseMoved
// TODO add your handling code here:
}//GEN-LAST:event_signupLabelMouseMoved

private void jLayeredPane1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseMoved
// TODO add your handling code here:
   
}//GEN-LAST:event_jLayeredPane1MouseMoved

private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
// TODO add your handling code here:
    
}//GEN-LAST:event_formMouseMoved

private void signupLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabelMouseClicked
    this.setVisible(false);
    Register register = new Register(this);
    register.setVisible(true);
}//GEN-LAST:event_signupLabelMouseClicked

private void setSomeConfiguration() {
    Configuration.HANDLE = handleField.getText();
}
private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    if(formComplete()) {
        adminService = new AdminService();
        if(adminService.loginAdmin(handleField.getText(), passwordField.getText())) {
            setSomeConfiguration();
            this.dispose();
            new Dashboard().setVisible(true);
        }
    }
}//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLoginLabel;
    private javax.swing.JTextField handleField;
    private javax.swing.JLabel handleLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel signupLabel;
    // End of variables declaration//GEN-END:variables

    private boolean formComplete() {
        if(handleField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill the handle");
        }
        else if(passwordField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill the password");
        }
        return true;
    }
}
